# Generated by Django 3.2.8 on 2021-12-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='commerce.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
