# Generated by Django 3.2.8 on 2021-12-08 06:03

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20211207_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(upload_to=commerce.models.upload_to),
        ),
    ]
